"""Project's constants. NOT used yet!"""

SITE_NAME = ''
SITE_SLOGAN = ''
META_DESCRIPTION = ''

LOGO_URL = ''
APPLE_TOUCH_ICON_URL = ''
FAVICON_URL = ''

META_AUTHOR = ''
META_REPLY_TO = ''
META_COPYRIGHT = ''
META_CREATOR = ''
META_PUBLISHER = ''

ADMIN_SITE_HEADER = ''
ADMIN_SITE_TITLE = ''
ADMIN_INDEX_TITLE = ''
