# Generated by Django 3.0.7 on 2020-06-28 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebs_duty_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='duty',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebs_duty_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='added_by',
            field=models.ForeignKey(blank=True, default=None, help_text='User who added the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebs_celebrity_adders', to=settings.AUTH_USER_MODEL, verbose_name='added by'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='duties',
            field=models.ManyToManyField(blank=True, help_text="Celebrities' duties in movies", related_name='celebs', to='celebs.Duty', verbose_name='duties'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, help_text='User who updated the db record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebs_celebrity_modifiers', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
    ]
