# Generated by Django 3.0.7 on 2020-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_auto_20200626_1924'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='celebrity',
            name='celebs_cele_first_n_c45950_gin',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='first_name_vector',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='last_name_vector',
        ),
        migrations.RemoveField(
            model_name='celebrity',
            name='name_vector',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='name_vector',
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='name',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='computed full name', max_length=245, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(db_index=True, max_length=245, unique=True, verbose_name='name'),
        ),
    ]
