# Generated by Django 3.0.7 on 2020-06-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0005_celebrity_imdb_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrity',
            options={'verbose_name': 'celebrity', 'verbose_name_plural': 'celebrities'},
        ),
    ]
