# Generated by Django 3.0.7 on 2020-06-26 19:24

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200626_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='pgrating',
            name='name_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
