# Generated by Django 3.0.7 on 2020-06-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200630_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_raters_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='IMDB raters count'),
        ),
    ]
