# Generated by Django 3.0.7 on 2020-06-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200626_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name_vector',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='name_vector',
        ),
        migrations.RemoveField(
            model_name='pgrating',
            name='name_vector',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=245, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pgrating',
            name='name',
            field=models.CharField(db_index=True, max_length=245, unique=True, verbose_name='name'),
        ),
    ]
