# Generated by Django 3.0.7 on 2020-06-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200626_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_link',
            field=models.URLField(blank=True, default='', verbose_name='IMDB URL'),
        ),
    ]
