# Generated by Django 3.0.7 on 2020-06-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_imdb_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='moviecrew',
            options={'verbose_name': 'movie crew', 'verbose_name_plural': 'movie crews'},
        ),
        migrations.AlterModelOptions(
            name='pgrating',
            options={'verbose_name': 'PG Rating', 'verbose_name_plural': 'PG Ratings'},
        ),
    ]
